### ISSUE TITLE
list_market_book not working?

### ISSUE THREAD

**Issue by thepanu** [mikecmpbll/betfair#1]
I have tried for a while now to get simple list_market_book working I constantly bump into "MandatoryNotDefined" error. There is good possibility that error is in my code, but it doesn't hurt to check.

I am able to get market catalogue just fine and to keep everything simple I have tried to fetch information for one marketId (1.118451619) and I was able to fo just that with following and was also able to put market id into variable (not really needed atm, but double checking)

```
soccer = client.list_market_catalogue({
    filter: {
        marketIds: [1.118451619] },
        maxResults: 200 
    })
id = soccer.first["marketId"]    
```

But when I try to fetch market book for that same id with following I get an error about mandatory no defined. Even though to my understanding marketid is the only required field for this.

```
book = client.list_market_book({
   filter: {
     marketIds: id }
})
```

Is it something I did or is there really an issue?

Error I get is: 

```
{"detail"=>{}, "faultcode"=>"Client", "faultstring"=>"DSC-0018"}
```

Which according to this https://github.com/betfair/cougar-documentation/blob/master/legacy/Cougar_Fault_Reporting.md is described as "A parameter marked as mandatory was not provided"

**Comment by mikecmpbll** [comment]
Looks like listMarketBook just takes the marketIds as a root parameter, rather than nested in filters (https://api.developer.betfair.com/services/webapps/docs/display/1smk3cen4v3lu3yomq5qye0ni/listMarketBook). It's also expecting an array value. The following works for me:

```
client.list_market_book({ marketIds: ["1.118451619"] })
```

returning:

```
[{"marketId"=>"1.118451619",
  "isMarketDataDelayed"=>false,
  "status"=>"OPEN",
  "betDelay"=>0,
  "bspReconciled"=>false,
  "complete"=>true,
  "inplay"=>false,
  "numberOfWinners"=>1,
  "numberOfRunners"=>3,
  "numberOfActiveRunners"=>3,
  "lastMatchTime"=>"2015-04-26T16:55:34.806Z",
  "totalMatched"=>4395.5,
  "totalAvailable"=>423908.05,
  "crossMatching"=>true,
  "runnersVoidable"=>false,
  "version"=>967232319,
  "runners"=>
   [{"selectionId"=>55270,
     "handicap"=>0.0,
     "status"=>"ACTIVE",
     "lastPriceTraded"=>2.0,
     "totalMatched"=>2368.15},
    {"selectionId"=>55265,
     "handicap"=>0.0,
     "status"=>"ACTIVE",
     "lastPriceTraded"=>4.1,
     "totalMatched"=>1833.26},
    {"selectionId"=>58805,
     "handicap"=>0.0,
     "status"=>"ACTIVE",
     "lastPriceTraded"=>3.9,
     "totalMatched"=>194.08}]}]
```

**Comment by thepanu** [comment]
Yup, works now. Thanks for the help.
