### ISSUE TITLE
[Question] - Listen for events

### ISSUE THREAD

**Issue by SylarRuby** [mikecmpbll/betfair#13]
Hi, thanks for creating a much loved ruby gem for betfair. Question. Does this works with `stream-api.betfair.com`? How about listening for events when using the non interactive login?

**Comment by mikecmpbll** [comment]
hey @SylarRuby . i'm not sure that existed when i originally wrote this, or if it did i definitely didn't factor it in :). so no, unfortunately not yet.

**Comment by SylarRuby** [comment]
Many thanks!
