### ISSUE TITLE
list_market_book(market_id), client returns {"detail"=>{}, "faultcode"=>"Client", "faultstring"=>"DSC-0008"}

### ISSUE THREAD

**Issue by rudedoc** [mikecmpbll/betfair#3]
Just checking out the gem. Using the example code I tried:

```
racing_markets.each do |market|
  client.list_market_book(market['marketId'])
end

```

it returns:
{"detail"=>{}, "faultcode"=>"Client", "faultstring"=>"DSC-0008"}

**Comment by mikecmpbll** [comment]
As per the [listMarketBook documentation](https://api.developer.betfair.com/services/webapps/docs/display/1smk3cen4v3lu3yomq5qye0ni/listMarketBook), you are required to supply a "marketIds" parameter. And you can list multiple markets in one call so no point looping and causing more noise on the API:

``` ruby
client.list_market_book(marketIds: racing_markets.map{ |m| m['marketId'] })
```

**Comment by rudedoc** [comment]
Correct!

Thanks for that and the great little gem!
