### ISSUE TITLE
Initialisation

### ISSUE THREAD

**Issue by systemshq** [mikecmpbll/betfair#4]
Not sure what I'm doing wrong here? Many thanks in advance.

[1] pry(main)> gem 'betfair-ng'
[2] pry(main)> client = Betfair::Client.new("X-Application" => "...............")
NameError: uninitialized constant Betfair

**Comment by mikecmpbll** [comment]
hi @systemshq. you only need the `gem` command if you're using Bundler and a Gemfile. If you want to have a play in irb then install the gem to your system with `gem install betfair-ng` at the command line. Then in irb just `require 'betfair'`.

**Comment by systemshq** [comment]
Rather nice. Many thanks!!

One more question please. in the Betfair non-interactive login documentation it discusses needing self signed ssl certs:-

https://api.developer.betfair.com/services/webapps/docs/display/1smk3cen4v3lu3yomq5qye0ni/Non-Interactive+%28bot%29+login

Yet your library doesn't make use of them? I'm not really too worried as when I log in via the web browser I'm also not using a self signed cert. However, since Betfair seem to have gone to a lot of trouble to get programmers to use self signed certs I was wondering what your rationale for not using them was please?

**Comment by mikecmpbll** [comment]
It's advisable to use the non-interactive login for bot login, as the documentation you pointed to suggests. This was added to betfair-ng by @paulgillard (https://github.com/mikecmpbll/betfair/pull/2) and released in v0.2.0.

Feel free to submit a pull request for the README if you want to update it to add info about [`non_interactive_login`](https://github.com/mikecmpbll/betfair/blob/master/lib/betfair/api/rest.rb#L44) :)

**Comment by systemshq** [comment]
Many thanks:):)
