### ISSUE TITLE
Marketbook request with EX Best Offers

### ISSUE THREAD

**Issue by acegilz** [mikecmpbll/betfair#8]
I am wondering how could I request the market-book with the best offers option.
Like this:
https://www.dropbox.com/s/awcseufzmkurpkf/Screenshot%202016-06-02%2003.10.35.png?dl=0

**Comment by mikecmpbll** [comment]
little late, but you'd probably want something like:

``` ruby
client.list_market_book({
  marketIds: ["...", "..."],
  priceProjection: { priceData: ["EX_BEST_OFFERS"] },
})
```
